version: '2'
services:
  elastic-erga:
    build:
      context: ../../
      dockerfile: devops/docker/app/Dockerfile
    ports:
      - "10080:80"
    links:
      - database
      - elasticsearch
    volumes:
      - ../../src:/var/www/elastic-erga
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=database
      - DB_DATABASE=elastic_erga
      - DB_USERNAME=elastic_erga
      - DB_PASSWORD=elastic_erga
      - TERM="xterm" # to make it easier to docker attach / exec

  database:
    image: mysql
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=unsafe-local-dev-only
      - MYSQL_USER=elastic_erga
      - MYSQL_PASSWORD=elastic_erga
      - MYSQL_DATABASE=elastic_erga

  elasticsearch:
    image: elasticsearch
    ports:
      - "19200:9200"